name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: latest

      - name: Start Docker Compose
        run: |
          docker-compose up -d

      - name: Run tests
        run: |
          docker exec -it covid-app python tests.py

      - name: Stop Docker Compose
        run: |
          docker-compose down